package com.wandrell.tabletop.rpg.pendragon.bundle;

import java.util.ListResourceBundle;

import com.wandrell.tabletop.rpg.pendragon.conf.PendragonLabels;

public class PendragonGlossaryBundle extends ListResourceBundle {
    static final Object[][] contents = {
	    // LOCALIZE THIS
	    { PendragonGlossaryBundleKeys.AGE, "Age" },
	    { PendragonGlossaryBundleKeys.ANIMALS, "Animals" },
	    { PendragonGlossaryBundleKeys.ANNOTATION, "annotation" },
	    { PendragonGlossaryBundleKeys.ANNUAL_GLORY, "Annual Glory" },
	    { "arabic", "Arabic" },
	    { PendragonGlossaryBundleKeys.ARMOR, "Armor" },
	    { PendragonGlossaryBundleKeys.ARMOR_KIND, "Armor kind" },
	    { PendragonGlossaryBundleKeys.BASE_GLORY, "Base glory" },
	    { PendragonGlossaryBundleKeys.BASE_VALUES, "Base values" },
	    { "bagpipes", "Bagpipes" },
	    { PendragonGlossaryBundleKeys.BONUS, "Bonus" },
	    { PendragonLabels.FLAGS_BREAKS_ENEMY_ON_DRAW,
		    "Breaks enemy weapon on draw" },
	    { PendragonLabels.FLAGS_BREAKS_ON_FUMBLE, "Breaks on fumble" },
	    { PendragonGlossaryBundleKeys.CHAIN_ARMOR, "Chain armor" },
	    { PendragonGlossaryBundleKeys.CHIVALDRY, "Chivaldry" },
	    { "christianity", "Christianity" },
	    { "city", "City" },
	    { "clan", "Clan" },
	    { PendragonGlossaryBundleKeys.COMBAT_TRAINABLE, "Combat trainable" },
	    { "commoners", "Commoners" },
	    { PendragonGlossaryBundleKeys.CULTURE, "Culture" },
	    { PendragonGlossaryBundleKeys.CURRENT_YEAR, "Current Year" },
	    { PendragonGlossaryBundleKeys.DATE, "Date" },
	    { PendragonGlossaryBundleKeys.DENARII, "Denarii" },
	    { PendragonGlossaryBundleKeys.DESCRIPTION, "Description" },
	    { PendragonGlossaryBundleKeys.DIE, "Die" },
	    { PendragonGlossaryBundleKeys.DICE_BONUS, "Dice bonus" },
	    { "doublepipes", "Double pipes" },
	    { "drums", "Drums" },
	    { PendragonLabels.VH_BONUS_DAMAGE_DIE, "Bonus dice" },
	    { PendragonLabels.VH_BONUS_DAMAGE_DIE_VS_CHAIN,
		    "Bonus dice vs. chain" },
	    { PendragonLabels.VH_BONUS_DAMAGE_DIE_VS_LEATHER,
		    "Bonus dice vs. leather" },
	    { PendragonLabels.VH_BONUS_DAMAGE_DIE_VS_PLATE,
		    "Bonus dice vs. plate" },
	    { PendragonLabels.VH_BONUS_DAMAGE_DIE_VS_SHIELD,
		    "Bonus dice vs. shield" },
	    { PendragonLabels.VH_BONUS_DAMAGE_DIE_VS_UNARMORED,
		    "Bonus dice vs. unarmoured" },
	    { PendragonGlossaryBundleKeys.EFFECTS, "Effects" },
	    { "emperor", "Emperor" },
	    { PendragonGlossaryBundleKeys.EQUIPABLE_ITEM, "Equipable item" },
	    { PendragonGlossaryBundleKeys.EQUIPMENT, "Equipment" },
	    { "family", "Family" },
	    { PendragonGlossaryBundleKeys.FATHER, "Father" },
	    { PendragonGlossaryBundleKeys.FATHER_CLASS_INHERITED_GLORY,
		    "Glory inherited from the father's class" },
	    { PendragonGlossaryBundleKeys.FATHER_GLORY, "Father's glory" },
	    { PendragonGlossaryBundleKeys.FATHER_CLASS, "Father's Class" },
	    { PendragonGlossaryBundleKeys.FATHER_NAME, "Father's Name" },
	    { PendragonGlossaryBundleKeys.FILES, "Files" },
	    { PendragonGlossaryBundleKeys.FLAGS, "Flags" },
	    { "flute", "Flute" },
	    { PendragonGlossaryBundleKeys.FOLLOWERS, "Followers" },
	    { PendragonGlossaryBundleKeys.GENERAL, "General" },
	    { PendragonGlossaryBundleKeys.GENTLEWOMAN, "Gentlewoman" },
	    { PendragonGlossaryBundleKeys.GLORY, "Glory" },
	    { PendragonGlossaryBundleKeys.GLORY_PER_YEAR, "Glory per year" },
	    { "glyphs", "Glyphs" },
	    { PendragonLabels.FLAGS_GOOD_VS_HORSEMEN, "Good against horsemen" },
	    { PendragonLabels.FLAGS_GOOD_VS_LANCE, "Good against lances" },
	    { "harp", "Harp" },
	    { PendragonGlossaryBundleKeys.HEAVY_LOAD, "Heavy load" },
	    { "history", "History" },
	    { PendragonGlossaryBundleKeys.HOLDINGS, "Holdings" },
	    { PendragonGlossaryBundleKeys.HOME, "Current home" },
	    { PendragonGlossaryBundleKeys.HOMELAND, "Homeland" },
	    { "horn", "Horn" },
	    { PendragonGlossaryBundleKeys.HORSES, "Horses" },
	    { PendragonGlossaryBundleKeys.HORSE_TYPE, "Horse type" },
	    { PendragonGlossaryBundleKeys.HUNTING_HORSE, "Hunting horse" },
	    { PendragonGlossaryBundleKeys.HUSBANDS, "Husbands" },
	    { PendragonLabels.FLAGS_HITS_BACK, "Hits back with a 1" },
	    { PendragonLabels.FLAGS_IGNORES_SHIELD, "Ignores shield" },
	    { PendragonGlossaryBundleKeys.INHERITED_GLORY, "Inherited glory" },
	    { "instrument", "Instrument" },
	    { PendragonGlossaryBundleKeys.KNIGHTED, "Knighted" },
	    { PendragonGlossaryBundleKeys.KNIGHTED_GLORY, "Knighted glory" },
	    { PendragonGlossaryBundleKeys.JOB, "Job" },
	    { PendragonGlossaryBundleKeys.KNIGHT, "Knight" },
	    { PendragonGlossaryBundleKeys.KNIGHTLY_ARMOR, "Knightly Armor" },
	    { PendragonGlossaryBundleKeys.LANDED, "Landed" },
	    { "latin", "Latin" },
	    { PendragonGlossaryBundleKeys.LEATHER_ARMOR, "Leather armor" },
	    { "levy", "Levy" },
	    { PendragonGlossaryBundleKeys.LIBRA, "Libra" },
	    { PendragonGlossaryBundleKeys.LIEGE, "Liege Lord" },
	    { "lord", "Lord" },
	    { "lute", "Lute" },
	    { PendragonGlossaryBundleKeys.MAY_WEAR_ARMOR, "May wear armor" },
	    { PendragonGlossaryBundleKeys.MAX, "Max." },
	    { PendragonGlossaryBundleKeys.MIN, "Min." },
	    { PendragonGlossaryBundleKeys.MONEY, "Money" },
	    { "music", "Music" },
	    { PendragonGlossaryBundleKeys.NAME, "Name" },
	    { "ogham", "Ogham" },
	    { "paganism", "Paganism" },
	    { PendragonGlossaryBundleKeys.PET, "Pet" },
	    { PendragonGlossaryBundleKeys.PLATE_ARMOR, "Plate armor" },
	    { PendragonGlossaryBundleKeys.PLAYER_NAME, "Player's Name" },
	    { PendragonGlossaryBundleKeys.QUANTITY, "Quantity" },
	    { PendragonGlossaryBundleKeys.RANGE, "Range" },
	    { PendragonLabels.VH_RANGE_LONG, "Maximum range for long range" },
	    { PendragonLabels.FLAGS_REDUCES_SHIELD_TO_ROLL,
		    "Reduces shield to a roll" }, { "recorder", "Recorder" },
	    { PendragonGlossaryBundleKeys.RELIGION, "Religion" },
	    { PendragonGlossaryBundleKeys.REROLL, "Reroll" },
	    { PendragonLabels.VH_REROLL_BONUS, "Reroll bonus" },
	    { "rerolls", "Rerolls" },
	    { PendragonGlossaryBundleKeys.REQUIREMENTS, "Requirements" },
	    { PendragonLabels.VH_ROUNDS_TO_RELOAD, "Rounds to reload" },
	    { PendragonGlossaryBundleKeys.RUINED, "Ruined" },
	    { "runes", "Runes" }, { "saxons", "Saxons" },
	    { PendragonGlossaryBundleKeys.SHIELD, "Shield" },
	    { PendragonGlossaryBundleKeys.SON_NUMBER, "Son Number" },
	    { PendragonGlossaryBundleKeys.SPOUSE, "Spouse" },
	    { PendragonGlossaryBundleKeys.SQUIRE, "Squire" },
	    { "symbols", "Symbols" }, { "titled", "Titled" },
	    { PendragonGlossaryBundleKeys.TITLES, "Titles" },
	    { PendragonGlossaryBundleKeys.TOTAL_ARMOR, "Total Armor" },
	    { PendragonGlossaryBundleKeys.TOTAL_GLORY, "Total Glory" },
	    { "trumpet", "Trumpet" }, { "type", "Type" },
	    { PendragonLabels.FLAGS_TWO_HANDED, "Two handed" },
	    { PendragonGlossaryBundleKeys.UNARMORED, "Unarmored" },
	    { PendragonGlossaryBundleKeys.VALUE, "Value" },
	    { PendragonLabels.DESCRIPTOR_VASSALS, "Vassals" },
	    { PendragonGlossaryBundleKeys.WEAPON, "Weapon" },
	    { PendragonGlossaryBundleKeys.WIVES, "Wives" },
	    { PendragonLabels.TEXT_WILL, "Will" },
	    { PendragonLabels.VH_WORTH, "Worth" },
	    { PendragonGlossaryBundleKeys.YEARS, "Years" },
	    { PendragonGlossaryBundleKeys.YEAR_BORN, "Year Born" },
	    { PendragonLabels.VH_YEARS_AGED, "Years aged" },
    // END OF MATERIAL TO LOCALIZE
    };

    @Override
    public Object[][] getContents() {
	return contents;
    }

}
