package com.wandrell.tabletop.pendragon.bundle;

import java.util.ListResourceBundle;

public class ItemsBundle extends ListResourceBundle {
    static final Object[][] contents = {
	    // LOCALIZE THIS
	    { "achilles_sweat", "Achilles' Sweat" },
	    { "ancestral_helm", "Ancestral Helm" },
	    { "ancestral_spinning_wheel", "Ancestral Spinning Wheel" },
	    { "ancient_bronze_sword_1", "Ancient bronze sword (+1)" },
	    { "ancient_bronze_sword_2", "Ancient bronze sword (+2)" },
	    { "ancient_gold_serpent_armband", "Ancient gold serpent armband" },
	    { "ancient_helmet", "Ancient helmet" },
	    { "ancient_iron_ring", "Ancient iron ring" },
	    { "ancient_shield", "Ancient shield" },
	    { "andvaris_bile", "Andvari's Bile" },
	    { "arm_band_gold", "Arm band (gold)" },
	    { "arm_band_silver", "Arm band (silver)" },
	    { "arm_ring_of_chastity", "Arm ring of chastity" },
	    { "armor_that_hates_beasts", "Armor that hates beasts" },
	    { "augustus_diadem", "Augustus' diadem" },
	    { "axe", "Axe" },
	    { "balders_charm", "Balder's Charm" },
	    { "bandage_of_great_effect", "Bandage of Great Effect" },
	    { "beags_water", "Beag's Water" },
	    { "belt_of_cupid", "Belt of Cupid" },
	    { "belt_of_the_salmon", "Belt of the Salmon" },
	    { "bible_of_ulfilias_an_arian_christian_holy_book",
		    "Bible of Ulfilias, an Arian Christian holy book" },
	    { "big_toe_of_saint_christopher", "Big Toe of Saint Christopher" },
	    { "billygoat_blood", "Billygoat Blood" },
	    { "blessed_lance_1", "Blessed Lance (+1)" },
	    { "blessed_lance_2", "Blessed Lance (+2)" },
	    { "blood_of_joseph_of_arimathea", "Blood of Joseph of Arimathea" },
	    { "blue_medicine_bottle", "Blue Medicine bottle" },
	    { "bone_fragment_of_saint_sebastian",
		    "Bone fragment of Saint Sebastian" },
	    { "borms_healing", "Borm's Healing" },
	    { "borvos_healing", "Borvo's Healing" },
	    { "bone_of_king_lucius", "Bone of king Lucius" },
	    { "book_of_asclepius", "Book of Asclepius" },
	    { "bow", "Bow" },
	    { "bow_of_saint_apollo", "Bow of Saint Apollo" },
	    { "bow_of_the_sun", "Bow of the Sun" },
	    { "bull_juice", "Bull Juice" },
	    { "caelius_aurelianus_medication", "Caelius Aurelianus' medication" },
	    { "cauldron_power", "Cauldron Power" },
	    { "centurions_lucky_helm", "Centurion's Lucky Helm" },
	    { "chainmail_open_helm", "Chainmail and open helm" },
	    { "chainmail_nasal_helm", "Chainmail and nasal helm" },
	    { "charmed_horn", "Charmed Horn" },
	    { "cloak_of_otter_fur", "Cloak of otter fur" },
	    { "clothing", "Clothing" },
	    { "coal_of_lug", "Coal of Lug" },
	    { "come_back_potion", "\"Come Back\" potion" },
	    { "compound_bow", "Compound bow" },
	    { "chain_of_ogma", "Chain of Ogma" },
	    { "christian_relic_bone", "Christian Relic (bone fragment)" },
	    { "christian_relic_blood", "Christian Relic (blood)" },
	    { "christian_relic_finger", "Christian Relic (finger)" },
	    { "christian_relic_hair", "Christian Relic (hair)" },
	    { "christian_relic_tears", "Christian Relic (tears)" },
	    { "comb_of_aengus", "Comb of Aengus" },
	    { "concentrated_billygoat_blood", "Concentrated Billygoat Blood" },
	    { "cuirbouilli_helm", "Cuirbouilli and helm" },
	    { "cuirbouilli_nasal_helm", "Cuirbouilli and nasal helm" },
	    { "crossbow", "Crossbow" },
	    { "dagger", "Dagger" },
	    { "dagger_of_retribution", "Dagger of retribution" },
	    { "dark_candle", "Dark candle" },
	    { "desert_falcon", "Desert Falcon" },
	    { "devils_own_venom", "Devil's Own Venom" },
	    { "dian_cechts_bandage", "Dian Cetcht's Bandage" },
	    { "dragons_venom", "Dragon's Venom" },
	    { "ear_of_saint_martin_the_soldier",
		    "Ear of Saint Martin the Soldier" },
	    { "elixir_of_song", "Elixir of Song" },
	    { "engraved_ring_gold", "Gold engraved ring" },
	    { "engraved_ring_silver", "Silver engraved ring" },
	    { "eyebrow_of_saint_finnian", "Eye brow of Saint Finnian" },
	    { "family_bandage_german", "Family bandage (German)" },
	    { "family_sword", "Family sword" },
	    { "fancy_harp", "Fancy harp" },
	    { "fantastic_dancing_shoes", "Fantastic dancing shoes" },
	    { "fantastic_globet", "Fantastic globet" },
	    { "fantastic_harp", "Fantastic harp" },
	    { "fantastic_helmet", "Fantastic helmet" },
	    { "fantastic_polar_bear_fur_cloak",
		    "Fantastic polar bear fur cloak" },
	    { "fantastic_running_boots", "Fantastic running boots" },
	    { "fantastic_saddle", "Fantastic saddle" },
	    { "fantastic_saddle_irish", "Fantastic saddle (Irish)" },
	    { "fantastic_sobriety_ring", "Fantastic Sobriety Ring" },
	    { "fantastic_stirrups", "Fantastic stirrups" },
	    { "fantastic_underjerkin", "Fantastic underjerkin" },
	    { "fantastic_globet", "Fantastic Globet" },
	    { "fantastic_pearl_box", "Fantastic Pearl Box" },
	    { "feather_of_saint_matthew", "Feather of Saint Matthew" },
	    { "finger_of_saint_alban", "Finger of Saint Alban" },
	    { "finger_of_saint_paul_of_tarsus",
		    "Finger of Saint Paul of Tarsus" },
	    { "fingernail_of_saint_cecelia", "Fingernail of Saint Cecelia" },
	    { "fingernail_of_saint_columba_the_virgin",
		    "Fingernail of Saint Columba the Virgin" },
	    { "flail", "Flail" },
	    { "fortuna_charm", "Fortuna Charm" },
	    { "freijas_embrace", "Freija's Embrace" },
	    { "freijas_touch", "Freija's Touch" },
	    { "full_plate_closed_helm", "Full plate and closed helm" },
	    { "fur_and_samite_cloak", "Fur and samite cloak" },
	    { "galens_healing_medicine", "Galen's healing medicine" },
	    { "gilded_helmet", "Gilded helmet" },
	    { "gladius_of_titus_pullo", "Gladius of Titus Pullo" },
	    { "good_snake_healing", "Good Snake Healing" },
	    { "good_snake_venom", "Good Snake Venom" },
	    { "golden_tear_of_the_sun_goddess",
		    "Golden tear of the Sun Goddess" },
	    { "gothic_plate_frog_helmet", "Gothic plate and frog helmet" },
	    { "grandpas_shield", "Grandpa's shield" },
	    { "great_axe", "Great axe" },
	    { "great_lance", "Great lance" },
	    { "great_mace", "Great mace" },
	    { "great_spear", "Great spear" },
	    { "great_sword", "Great sword" },
	    { "green_medicine_bottle", "Green Medicine bottle" },
	    { "halberd", "Halberd" },
	    { "hammer", "Hammer" },
	    { "hard_leather", "Hard leather" },
	    { "harp_of_finn", "Harp of Finn" },
	    { "harp_of_dagda", "Harp of Dagda" },
	    { "healing_ring", "Healing Ring" },
	    { "heater", "Heater" },
	    { "heavy_clothing", "Heavy clothing" },
	    { "heavy_crossbow", "Heavy crossbow" },
	    { "heavy_scale_mail_closed_helm",
		    "Heavy scale mail and closed helm" },
	    { "helmet_of_terror", "Helmet of Terror" },
	    { "hernes_blood", "Herne's Blood" },
	    { "highland_pony_rouncy", "Highland pony, rouncy" },
	    { "horatios_shield", "Horatio's shield" },
	    { "horn_of_santiago", "Horn of Santiago" },
	    { "horse_hair_from_eponas_horse", "Horse hair from Epona's hair" },
	    { "hyrkanian_drink", "Hyrkanian Drink" },
	    { "improved_chainmail_closed_helm",
		    "Improved chainmail and closed helm" },
	    { "institutes_of_gaius_a_book_of_law",
		    "Institutes of Gaius, a book of law" },
	    { "ivory_draughts_game", "Ivory draughts game" },
	    { "ivory_horn_drink", "Ivory Horn Drink" },
	    { "javelin", "Javelin" },
	    { "jewel_of_beauty", "Jewel of Beauty" },
	    { "jewel_of_chastity", "Jewel of Chastity" },
	    { "jewel_of_discerning", "Jewel of Discerning" },
	    { "jewel_of_temperance", "Jewel of Temperance" },
	    { "justice_ring", "Justice Ring" },
	    { "junos_needle", "Juno's Needle" },
	    { "keen_razor", "Keen Razor" },
	    { "kidney_of_saint_damian", "Kidney of Saint Damian" },
	    { "kontos", "Kontos" },
	    { "lance", "Lance" },
	    { "lears_tears", "Lear's Tears" },
	    { "leather_armor", "Leather armor" },
	    { "legionnaires_shield", "Legionnaires shield" },
	    { "ligament_of_saint_cosmas", "Ligament of Saint Cosmas" },
	    { "light_crossbow", "Light crossbow" },
	    { "light_shield", "Light shield" },
	    { "little_toe_of_saint_christopher",
		    "Little Toe of Saint Christopher" },
	    { "lock_of_gwydions_hair", "Lock of Gwydion's hair" },
	    { "lock_of_arianrohds_hair", "Lock of Arianrhod's hair" },
	    { "longbow", "Longbow" },
	    { "lucky_axe", "Lucky axe" },
	    { "lucky_dice", "Lucky dice" },
	    { "lucky_javelin", "Lucky javeling" },
	    { "luxovius_potion", "Luxovious' Potion" },
	    { "luxurious_cloak", "Luxurious cloak" },
	    { "luxurious_fur_cloak", "Luxurious fur cloak" },
	    { "mace", "Mace" },
	    { "magic_healing_potion", "Magic healing potion" },
	    { "magical_boar_tatoo", "Magical Boar tatoo" },
	    { "magical_celestial_antler", "Magical celestial antler" },
	    { "magical_deer_boots", "Magical deer boots" },
	    { "magical_deer_tatoo", "Magical deer tatoo" },
	    { "magical_eagle_tatoo", "Magical eagle tatoo" },
	    { "magical_ermine_cloak", "Magical ermine cloak" },
	    { "magical_goat_tatoo", "Magical goat tatoo" },
	    { "magical_hawk_tatoo", "Magical hawk tatoo" },
	    { "magical_leaping_boots", "Magical leaping boots" },
	    { "magical_lynx_tatoo", "Magical lynx tatoo" },
	    { "magical_quiver", "Magical quiver" },
	    { "magical_salmon_tatoo", "Magical salmon tatoo" },
	    { "magical_sleep_stick", "Magical sleep stick" },
	    { "magical_stag_boots", "Magical stag boots" },
	    { "magical_wolf_cloak", "Magical wolf cloak" },
	    { "mark_of_the_hammer", "Mark of the hammer" },
	    { "mark_of_the_spear", "Mark of the spear" },
	    { "martins_liquid", "Martin's Liquid" },
	    { "marvelous_family_axe", "Marvelous family axe" },
	    { "marvelous_horsesoes", "Marvelous horsesoes" },
	    { "marvelous_iron_chain", "Marvelous iron chain" },
	    { "marvelous_listening_ring", "Marvelous listening ring" },
	    { "marvelous_saddle", "Marvelous saddle" },
	    { "marvelous_shield_christian", "Marvelous shield (Christian)" },
	    { "marvelous_shield_danish", "Marvelous shield (Danish)" },
	    { "marvelous_shield_pagan", "Marvelous shield (Pagan)" },
	    { "marvelous_sword", "Marvelous sword" },
	    { "marvelous_underjerkin", "Marvelous underjerkin" },
	    { "marvelous_whetstone", "Marvelous Whetstone" },
	    { "medium_crossbow", "Medium crossbow" },
	    { "metamorphosis_a_book_of_poetry",
		    "Metamorphosis, a book of poetry" },
	    { "miachs_ointment", "Miach's Ointment" },
	    { "military_hammer", "Military hammer" },
	    { "modrons_ointment", "Modron's Ointment" },
	    { "moon_potion", "Moon potion" },
	    { "morning_star", "Morning star" },
	    { "neros_harp", "Nero's Harp" },
	    { "old_war_booty_shield", "Old war booty shield" },
	    { "partial_plate_closed_helm", "Partial plate and closed helm" },
	    { "padded_armor", "Padded armor" },
	    { "perfect_scissors", "Perfect Scissors" },
	    { "phols_charm", "Phol's charm" },
	    { "phols_great_ointment", "Phol's great ointment" },
	    { "phols_healing_rock", "Phol's healing rock" },
	    { "phols_lesser_ointment", "Phol's lesser ointment" },
	    { "physiologus", "Physiologus" },
	    { "plate_reinforced_helm", "Plate and reinforced helm" },
	    { "plume_for_helmet", "Plume for helmet" },
	    { "poets_gift", "Poet's Gift" },
	    { "prescription_of_scribonius_largus_a_medicine",
		    "Prescription of Scribonius Largus, a medicine" },
	    { "protective_ring", "Protective Ring" },
	    { "quiver_of_golden_arrows", "Quiver of Golden Arrows" },
	    { "rainbow_great_axe", "Rainbow great axe" },
	    { "rainbow_great_sword", "Rainbow great sword" },
	    { "raven_feather_cloak", "Raven feather cloak" },
	    { "red_honey_bragget", "Red Honey Bragget" },
	    { "red_medicine_bottle", "Red Medicine bottle" },
	    { "reinforced_chainmail_closed_helm",
		    "Reinforced chainmail and closed helm" },
	    { "reinforced_plate_closed_helm",
		    "Reinforced plate and closed helm" },
	    { "ring_against_beasts", "Ring Against Beasts" },
	    { "ring_blessed_by_the_pope", "Ring blessed by the Pope" },
	    { "ring_of_beasts", "Ring of Beasts" },
	    { "ring_of_chastity", "Ring of Chastity" },
	    { "ring_of_seduction", "Ring of Seduction" },
	    { "rose_ointment", "Rose Ointment" },
	    { "sailor_tattoos", "Sailor Tattoos" },
	    { "scale_mail_open_helm", "Scale mail and open helm" },
	    { "scimitar", "Scimitar" },
	    { "seductive_perfume", "Seductive Perfume" },
	    { "serpent_venom", "Serpent Venom" },
	    { "shield", "Shield" },
	    { "shield_of_lucius_varenus", "Shield of Lucius Varenus" },
	    { "silver_love_ring", "Silver Love Ring" },
	    { "singing_blanket", "Singing blanket" },
	    { "small_shield", "Small shield" },
	    { "spear", "Spear" },
	    { "spearhead_of_odin", "Spearhead of Odin" },
	    { "spearhead_of_saint_george", "Spearhead of Saint George" },
	    { "spirit_blessing", "Spirit blessing" },
	    { "stoiks_temperance_drops", "Stoik's Temperance Drops" },
	    { "strong_shield", "Strong shield" },
	    { "suns_blessing", "Sun's Blessing" },
	    { "super_sharp_scimitar", "Super sharp scimitar" },
	    { "sword", "Sword" },
	    { "sword_belt", "Sword belt" },
	    { "sword_belt", "Sword belt" },
	    { "ten_feathers_of_aengus", "Ten feathers of Aengus" },
	    { "the_coin_named_makesgold", "The coin named Makesgold" },
	    { "the_expedition_anabasis", "The Expedition (Anabasis)" },
	    { "the_great_spear_piercer", "The great spear Piercer" },
	    { "the_hat", "\"The Hat\"" },
	    { "the_miraculous_medication_of_sextus_empiricus",
		    "The miraculous medication of Sextus Empiricus" },
	    { "thors_belt", "Thor's Belt" },
	    { "three_hairs_of_saint_patrick", "Three hairs of Saint Patrick" },
	    { "three_threads_of_saint_georges_cloak",
		    "Three threads of Saint George's cloak" },
	    { "thunor_charm", "Thunor Charm" },
	    { "troubadours_book_of_poetry", "Troubadour's Book of Poetry" },
	    { "tiwaz_charm", "Tiwaz Charm" },
	    { "tooth_of_cerberus", "Tooth of Cerberus" },
	    { "tooth_of_saint_germanus", "Tooth of Saint Germanus" },
	    { "torch_of_saint_brigit", "Torch of Saint Brigit" },
	    { "trust_drops", "Trust Drops" },
	    { "unicorn_horn_instrument", "Unicorn horn instrument" },
	    { "upright_boots", "Upright boots" },
	    { "vitality_belt", "Vitality belt" },
	    { "valuable_cloak_byzantium", "Valuable cloak (Byzantium)" },
	    { "valuable_cloak_germany", "Valuable cloak (Germany)" },
	    { "valuable_cloak_rome", "Valuable cloak (Rome)" },
	    { "valuable_cloak_spain", "Valuable cloak (Spain)" },
	    { "veronicas_tears", "Veronica's Tears" },
	    { "venus_perfume", "Venus Perfume" },
	    { "vestas_incense", "Vesta's Incense" },
	    { "vial_of_blood_of_saint_james_the_greater",
		    "Vial of blood of Saint James the Greater" },
	    { "vial_of_blood_of_saint_paul", "Vial of blood of Saint Paul" },
	    { "vial_of_blood_of_saint_peter", "Vial of blood of Saint Peter" },
	    { "vial_of_tears_of_saint_agnes_of_rome",
		    "Vial of tears of Saint Agnes of Rome" },
	    { "vial_of_water_from_the_jordan_river",
		    "Vial of water from the Jordan River" },
	    { "visionary_necklace", "Visionary Necklace" },
	    { "war_pony_trained_only_for_the_owner",
		    "War pony, trained only for the owner" },
	    { "warflail", "Warflail" }, { "warrior_song", "Warrior song" },
	    { "wild_healing_potion", "Wild healing potion" },
	    { "wondrous_flint_axe", "Wondrous flint axe" },
	    { "wondrous_globet", "Wondrous Globet" },
	    { "wondrous_sword_belt", "Wondrous Sword Belt" },
	    { "wotan_charm", "Wotan Charm" },
    // END OF MATERIAL TO LOCALIZE
    };

    @Override
    public Object[][] getContents() {
	return contents;
    }

}
